# Generated by Django 3.0.2 on 2020-02-04 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_mail',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
